<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Edição de turma</title>
</head>
<body>
  <form action="/highschool/index.php?controller=turma&action=gravar" method="post">
  
    Nome: <input type="text" name="nome" value="<?=$this->turma->getNome()?>"><br> 
    
    <input type="hidden" name="id" value="<?=$this->turma->getId()?>"><br> 
    
    <input type="submit" value="gravar">
    
  </form>
</body>
</html>
