<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Edição de aluno</title>
</head>
<body>
  <form action="/highschool/index.php?controller=aluno&action=gravar" method="post">
    Matrícula: 
    <input type="text" name="matricula" value="<?=$this->aluno->getMatricula()?>"><br>
    
    Nome:
    <input type="text" name="nome" value="<?=$this->aluno->getNome()?>"><br>
    
    Data de Nascimento:
    <input type="text" name="data_de_nascimento" value="<?=$this->aluno->getDataDeNascimento()?>"><br>
    
    Turma:
    <select name="turma">
      <?=$this->optionsTurma?>
    </select><br>
    
    <input type="hidden" name="id" value="<?=$this->aluno->getId()?>"><br>
    <input type="submit" value="gravar">
  </form>
</body>
</html>
